package io.rapidz.assignment1.ui

import androidx.compose.ui.graphics.Color

// Default Theme
val md_theme_default_primary = Color(0xFF6750A4)
val md_theme_default_onPrimary = Color(0xFFFFFFFF)
val md_theme_default_primaryContainer = Color(0xFFEADDFF)
val md_theme_default_onPrimaryContainer = Color(0xFF21005D)
val md_theme_default_secondary = Color(0xFF625B71)
val md_theme_default_onSecondary = Color(0xFFFFFFFF)
val md_theme_default_secondaryContainer = Color(0xFFE8DEF8)
val md_theme_default_onSecondaryContainer = Color(0xFF1D192B)
val md_theme_default_tertiary = Color(0xFF7D5260)
val md_theme_default_onTertiary = Color(0xFFFFFFFF)
val md_theme_default_tertiaryContainer = Color(0xFFFFD8E4)
val md_theme_default_onTertiaryContainer = Color(0xFF31111D)
val md_theme_default_error = Color(0xFFB3261E)
val md_theme_default_onError = Color(0xFFFFFFFF)
val md_theme_default_errorContainer = Color(0xFFF9DEDC)
val md_theme_default_onErrorContainer = Color(0xFF410E0B)
val md_theme_default_outline = Color(0xFF79747E)
val md_theme_default_background = Color(0xFFFFFBFE)
val md_theme_default_onBackground = Color(0xFF1C1B1F)
val md_theme_default_surface = Color(0xFFFFFBFE)
val md_theme_default_onSurface = Color(0xFF1C1B1F)
val md_theme_default_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_default_onSurfaceVariant = Color(0xFF49454F)
val md_theme_default_inverseSurface = Color(0xFF313033)
val md_theme_default_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_default_inversePrimary = Color(0xFFD0BCFF)
val md_theme_default_surfaceTint = Color(0xFF6750A4)
val md_theme_default_outlineVariant = Color(0xFFCAC4D0)
val md_theme_default_scrim = Color(0xFF000000)

// Admin Theme
val md_theme_admin_primary = Color(0xFFC00003)
val md_theme_admin_onPrimary = Color(0xFFFFFFFF)
val md_theme_admin_primaryContainer = Color(0xFFFFDAD5)
val md_theme_admin_onPrimaryContainer = Color(0xFF410000)
val md_theme_admin_secondary = Color(0xFF775651)
val md_theme_admin_onSecondary = Color(0xFFFFFFFF)
val md_theme_admin_secondaryContainer = Color(0xFFFFDAD5)
val md_theme_admin_onSecondaryContainer = Color(0xFF2C1512)
val md_theme_admin_tertiary = Color(0xFF705C2E)
val md_theme_admin_onTertiary = Color(0xFFFFFFFF)
val md_theme_admin_tertiaryContainer = Color(0xFFFCDFA6)
val md_theme_admin_onTertiaryContainer = Color(0xFF251A00)
val md_theme_admin_error = Color(0xFFBA1A1A)
val md_theme_admin_errorContainer = Color(0xFFFFDAD6)
val md_theme_admin_onError = Color(0xFFFFFFFF)
val md_theme_admin_onErrorContainer = Color(0xFF410002)
val md_theme_admin_background = Color(0xFFFFFBFF)
val md_theme_admin_onBackground = Color(0xFF201A19)
val md_theme_admin_surface = Color(0xFFFFFBFF)
val md_theme_admin_onSurface = Color(0xFF201A19)
val md_theme_admin_surfaceVariant = Color(0xFFF5DDDA)
val md_theme_admin_onSurfaceVariant = Color(0xFF534341)
val md_theme_admin_outline = Color(0xFF857370)
val md_theme_admin_inverseOnSurface = Color(0xFFFBEEEC)
val md_theme_admin_inverseSurface = Color(0xFF362F2E)
val md_theme_admin_inversePrimary = Color(0xFFFFB4A8)
val md_theme_admin_surfaceTint = Color(0xFFC00003)
val md_theme_admin_outlineVariant = Color(0xFFD8C2BE)
val md_theme_admin_scrim = Color(0xFF000000)